version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-bupsya496ic5"
s3_prefix = "sam-api"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
