service: lambda-sqs-lambda # 定义服务的名称

provider:
  name: aws # 云服务商为 aws
  runtime: nodejs14.x # 运行时 node 的版本
  region: eu-west-1 # 发布到 northeast region，其实就是东京 region
  stage: dev # 发布环境为 dev
  iamRoleStatements: # 创建 IAM role，允许 lambda function 向队列发送消息
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - Fn::GetAtt: [ receiverQueue, Arn ]
      
functions: # 定义两个 lambda functions
  order:
    handler: app/order.checkout # 第一个 lambda function 程序入口是 app 目录下的 order.js 里面的 checkout 方法
    events:	# trigger 触发器是 API Gateway 的方式，当接收到 /order 的 POST 请求时触发该 lambda function
      - http:
          method: post
          path: order

  invoice:
    handler: app/invoice.generate # 第二个 lambda function 程序入口是 app 目录下的 invoice.js 里面的 generate 方法
    timeout: 30
    events: # trigger 触发器是 SQS 服务，消息队列有消息时触发该 lambda function 消费消息
      - sqs:
          arn:
            Fn::GetAtt:
              - receiverQueue
              - Arn
resources:
  Resources:
    receiverQueue: # 定义 SQS 服务，也是 Lambda 需要依赖的服务
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.conf.queueName}

# package:
#   exclude:
#     - node_modules/**

custom: 
  conf: ${file(conf/config.json)} # 引入外部定义的配置变量
